# Generated by Django 6.0.4 on 2026-04-26 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='', max_length=20)),
                ('education_level', models.CharField(blank=True, default='', max_length=100)),
                ('profession', models.CharField(blank=True, default='', max_length=100)),
                ('short_bio', models.TextField(blank=True, default='')),
                ('serious_intention', models.CharField(blank=True, choices=[('marriage_soon', 'Marriage soon'), ('marriage_later', 'Marriage later'), ('family_discussion', 'Family discussion needed')], default='', max_length=30)),
                ('preferred_age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_country', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_city', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_education_level', models.CharField(blank=True, default='', max_length=100)),
                ('important_values', models.TextField(blank=True, default='')),
                ('show_photo', models.BooleanField(default=False)),
                ('show_city', models.BooleanField(default=True)),
                ('show_profession', models.BooleanField(default=True)),
                ('private_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matchmaking Profile',
                'verbose_name_plural': 'Matchmaking Profiles',
            },
        ),
    ]
